### ISSUE TITLE
Please upgrade the PyPI package 

### ISSUE THREAD

**Issue by filak** [dymmond/flask-esearch#1]
Thank you for the extension, it saved me some time !

I can confirm it works with the newest ES https://github.com/elastic/elasticsearch-py/releases/tag/v7.11.0 (and Flask 1.1.2)

I have not tested ELASTICSEARCH_HTTP_AUTH property but ELASTICSEARCH_HOST works fine.

**Comment by filak** [comment]
I can confirm that this extension works with newer ES versions - tested up to 7.15.2

Would you be so kind and update the package setup ?

    install_requires=[
        'Flask>=1.1.2',
        'Elasticsearch>=6.4.6,<=7.7.1',
        'Elasticsearch-dsl>=6.4.6,<=7.2.1'
    ],

**Comment by dymmonds** [comment]
Hi @filak apologies for not coming back to you so soon but I would like to tell you that your PR was merged and the new version 0.4.0 is out. 

Thank you for your contribution

**Comment by filak** [comment]
Thanks!
